// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJaZeAdYOHJm-aAbKjWAP_ABU0OGNFC8',
    appId: '1:485417259709:web:aa59110cd325d4cc9d1dd4',
    messagingSenderId: '485417259709',
    projectId: 'mobiluygulamagelistirme-d5e34',
    authDomain: 'mobiluygulamagelistirme-d5e34.firebaseapp.com',
    storageBucket: 'mobiluygulamagelistirme-d5e34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhOWRYfYjL-pe1lCHAa7Poy8lxRwbqYFc',
    appId: '1:485417259709:android:fea0a811e4d47a549d1dd4',
    messagingSenderId: '485417259709',
    projectId: 'mobiluygulamagelistirme-d5e34',
    storageBucket: 'mobiluygulamagelistirme-d5e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMss6pr-3n269LfFU0btF2hg9DmcHErE',
    appId: '1:485417259709:ios:12834a2fc4edb1749d1dd4',
    messagingSenderId: '485417259709',
    projectId: 'mobiluygulamagelistirme-d5e34',
    storageBucket: 'mobiluygulamagelistirme-d5e34.firebasestorage.app',
    iosBundleId: 'com.example.mobiluygulamagelistirme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkMss6pr-3n269LfFU0btF2hg9DmcHErE',
    appId: '1:485417259709:ios:12834a2fc4edb1749d1dd4',
    messagingSenderId: '485417259709',
    projectId: 'mobiluygulamagelistirme-d5e34',
    storageBucket: 'mobiluygulamagelistirme-d5e34.firebasestorage.app',
    iosBundleId: 'com.example.mobiluygulamagelistirme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFJaZeAdYOHJm-aAbKjWAP_ABU0OGNFC8',
    appId: '1:485417259709:web:1e21220b30b8b1849d1dd4',
    messagingSenderId: '485417259709',
    projectId: 'mobiluygulamagelistirme-d5e34',
    authDomain: 'mobiluygulamagelistirme-d5e34.firebaseapp.com',
    storageBucket: 'mobiluygulamagelistirme-d5e34.firebasestorage.app',
  );
}
